apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dac-member2
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dac-member2
  template:
    metadata:
      labels:
        app: dac-member2
    spec:
      containers:
      - name: member2
        image: ghcr.io/marigold-dev/dac-baseimage:master_a78b70c7_20230724101956
        command: ["/bin/bash", "/scripts/member2.sh"]
        env:
        - name: WIPE_MEMBER_2_DIR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: WIPE_MEMBER_2_DIR
        - name: WIPE_MEMBER_2_REVEAL_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: WIPE_MEMBER_2_REVEAL_DATA_DIR
        - name: WIPE_MEMBER_2_OCTEZ_CLIENT_DIR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: WIPE_MEMBER_2_OCTEZ_CLIENT_DIR
        - name: OCTEZ_CLIENT_DIR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: OCTEZ_CLIENT_DIR
        - name: MEMBER_2_DIR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: MEMBER_2_DIR
        - name: MEMBER_2_REVEAL_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: MEMBER_2_REVEAL_DATA_DIR
        - name: TEZOS_RPC
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: TEZOS_RPC
        - name: ALIAS_ROLLUP_OPERATOR
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: ALIAS_ROLLUP_OPERATOR
        - name: ALIAS_MEMBER_1
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: ALIAS_MEMBER_1
        - name: ALIAS_MEMBER_2
          valueFrom:
            configMapKeyRef:
              name: dac-node-env-vars-configmap
              key: ALIAS_MEMBER_2
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /health/live
            port: 11112
          initialDelaySeconds: 40
          periodSeconds: 20
          failureThreshold: 3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 11112
          protocol: TCP
          name: rpc
        volumeMounts:
        - name: dac-member2-dir-volume
          mountPath: /mounted_volume/dac/member-2
          readOnly: false
        - name: dac-member2-reveal-dir-volume
          mountPath: /mounted_volume/dac/member-2/reveals
          readOnly: false
        - name: dac-scripts-configmap
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: dac-member2-dir-volume
        persistentVolumeClaim:
          claimName: dac-member2-dir-volume
      - name: dac-member2-reveal-dir-volume
        persistentVolumeClaim:
          claimName: dac-member2-reveal-dir-volume
      - name: dac-scripts-configmap
        configMap:
          name: dac-scripts-configmap
