kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dac-coordinator-dir-volume
spec:
  storageClassName: "pd-ssd-retain"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dac-coordinator-reveal-dir-volume
spec:
  storageClassName: "pd-ssd-retain"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
