kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dac-rollup-import-volume
spec:
  storageClassName: "pd-ssd-retain"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dac-rollup-observer-shared-volume
spec:
  storageClassName: "pd-ssd-retain"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 25Gi
